"""Presentation-only construction; application behavior stays in SpotlightApp."""

from PyQt6.QtCore import Qt
from PyQt6.QtGui import QColor, QFont
from PyQt6.QtWidgets import (
    QFrame,
    QGraphicsDropShadowEffect,
    QHBoxLayout,
    QLabel,
    QMenu,
    QTextBrowser,
    QVBoxLayout,
    QWidget,
)

from backend.user_settings import settings_store
from frontend.brand import brand_pixmap
from frontend.companion import CompanionAvatar
from frontend.design import STYLE, ActionCard, ComposerFrame, StatusLabel, button
from frontend.history_input import HistoryLineEdit
from frontend.micro_motion import ActivityDots, MotionButton


def build_interface(window):
    ui = window.ui_text

    def label(source=""):
        widget = QLabel()
        ui.bind(widget, "setText", source)
        return widget

    def control(name, tip, callback, text="", primary=False):
        widget = button(name, ui(tip), callback, ui(text), primary=primary)
        ui.bind(widget, "setToolTip", tip)
        ui.bind(widget, "setAccessibleName", tip)
        if text:
            ui.bind(widget, "setText", text)
        return widget

    def action(menu, source, callback):
        item = menu.addAction(ui(source), callback)
        ui.bind(item, "setText", source)
        return item
    outer = QWidget()
    outer.setObjectName("outer")
    outer_layout = QVBoxLayout(outer)
    window.outer_layout = outer_layout
    outer_layout.setContentsMargins(12, 12, 12, 12)
    window.setCentralWidget(outer)
    window.container = QFrame()
    window.container.setObjectName("container")
    shadow = QGraphicsDropShadowEffect(window)
    shadow.setBlurRadius(24)
    shadow.setOffset(0, 5)
    shadow.setColor(QColor(0, 0, 0, 140))
    window.container.setGraphicsEffect(shadow)
    outer_layout.addWidget(window.container)
    root = QVBoxLayout(window.container)
    window.root_layout = root
    root.setContentsMargins(18, 12, 18, 14)
    root.setSpacing(12)

    window.notch_button = MotionButton()
    window.notch_button.setObjectName("notchButton")
    window.notch_button.setFixedHeight(36)
    window.notch_button.setCursor(Qt.CursorShape.PointingHandCursor)
    ui.bind(window.notch_button, "setAccessibleName", "Nexus sohbetini aç")
    ui.bind(window.notch_button, "setToolTip", "Üzerine gel: mini panel · Tıkla: sohbet")
    window.notch_button.clicked.connect(window.open_full_chat)
    notch = QHBoxLayout(window.notch_button)
    notch.setContentsMargins(18, 0, 18, 0)
    notch.setSpacing(8)
    window.notch_avatar = CompanionAvatar(28)
    window.notch_avatar.ambient_enabled = False
    notch.addWidget(window.notch_avatar)
    notch_name = QLabel("Nexus")
    notch_name.setObjectName("notchName")
    notch_name.setAttribute(Qt.WidgetAttribute.WA_TransparentForMouseEvents)
    notch.addWidget(notch_name, 1)
    window.notch_indicator = QLabel()
    window.notch_indicator.setFixedSize(6, 6)
    window.notch_indicator.setAttribute(Qt.WidgetAttribute.WA_TransparentForMouseEvents)
    notch.addWidget(window.notch_indicator)
    root.addWidget(window.notch_button)

    header = QWidget()
    window.header = header
    header.setObjectName("header")
    header_layout = QHBoxLayout(header)
    header_layout.setContentsMargins(0, 0, 0, 0)
    mark = QLabel()
    mark.setObjectName("brandMark")
    mark.setPixmap(brand_pixmap(22, tile=False))
    header_layout.addWidget(mark)
    brand = QLabel("nexus")
    brand.setObjectName("brand")
    header_layout.addWidget(brand)
    header_layout.addSpacing(12)
    window.home_tab = control("home", "Kontrol paneli", lambda: window.set_shell_mode("dock"), "Panel")
    window.chat_tab = control("chat", "Sohbeti aç", lambda: window.set_shell_mode("chat"), "Sohbet")
    for tab in (window.home_tab, window.chat_tab):
        tab.setObjectName("navigationTab")
        header_layout.addWidget(tab)
    header_layout.addStretch()
    for name, tip, callback in (
        ("plus", "Yeni sohbet · Ctrl+N", window.new_conversation),
        ("history", "Geçmiş · Ctrl+H", window.open_history),
        ("settings", "Ayarlar · Ctrl+,", window.open_settings),
        ("hide", "Küçült · Esc", window.collapse_to_notch),
    ):
        header_layout.addWidget(control(name, tip, callback))
    root.addWidget(header)

    window.dock_overview = QFrame()
    window.dock_overview.setObjectName("dockOverview")
    dock = QVBoxLayout(window.dock_overview)
    dock.setContentsMargins(0, 0, 0, 0)
    dock.setSpacing(6)
    overview = QHBoxLayout()
    overview.setSpacing(10)
    window.dock_avatar = CompanionAvatar(64)
    overview.addWidget(window.dock_avatar)
    activity = QVBoxLayout()
    activity.setSpacing(5)
    window.dock_title = QLabel(ui("Nexus hazır"))
    window.dock_title.setObjectName("dockTitle")
    activity.addWidget(window.dock_title)
    window.dock_status = StatusLabel(ui("Bir soru sor veya araç seç."))
    window.dock_status.setObjectName("dockStatus")
    activity.addWidget(window.dock_status)
    activity.addStretch()
    overview.addLayout(activity, 1)
    window.pin_button = control("pin", "Mini paneli sabitle", lambda: window.notch_controller.toggle_pin())
    window.pin_button.setCheckable(True)
    window.pin_button.setFixedSize(28, 28)
    overview.addWidget(window.pin_button)
    collapse = control("hide", "Küçült", window.collapse_to_notch)
    collapse.setFixedSize(28, 28)
    overview.addWidget(collapse)
    dock.addLayout(overview)
    quick = QHBoxLayout()
    quick.setSpacing(7)
    window.dock_tools = []
    for name, caption, callback in (
        ("document", "Belge ekle", window.import_document),
        ("memory", "Hafıza", lambda: window.open_memory_manager()),
        ("web", "Araştır", window.start_research),
        ("mic", "Sesli konuş", window.toggle_voice_recording),
    ):
        tool = control(name, caption, callback, caption)
        tool.setObjectName("dockTool")
        tool.setMinimumWidth(0)
        tool.setFixedHeight(32)
        quick.addWidget(tool, 1)
        window.dock_tools.append(tool)
    dock.addLayout(quick)
    mini_footer = QHBoxLayout()
    window.mini_badge = QLabel(ui("YEREL MODEL"))
    window.mini_badge.setObjectName("localBadge")
    mini_footer.addWidget(window.mini_badge)
    mini_footer.addStretch()
    mini_footer.addWidget(control("settings", "Ayarlar · Ctrl+,", window.open_settings))
    mini_footer.addWidget(control("chat", "Sohbeti aç", window.open_full_chat, "Sohbeti aç"))
    dock.addLayout(mini_footer)
    root.addWidget(window.dock_overview)

    content = QWidget()
    content.setObjectName("content")
    window.chat_content = content
    chat_columns = QHBoxLayout(content)
    chat_columns.setContentsMargins(0, 0, 0, 0)
    chat_columns.setSpacing(14)
    transcript = QWidget()
    content_layout = QVBoxLayout(transcript)
    content_layout.setContentsMargins(8, 0, 8, 0)
    content_layout.setSpacing(12)
    window.welcome = QWidget()
    window.welcome.setObjectName("welcome")
    welcome = QVBoxLayout(window.welcome)
    welcome.setContentsMargins(0, 8, 0, 2)
    welcome.setSpacing(12)
    welcome.addStretch(2)
    hero = CompanionAvatar(136)
    window.hero_logo = hero
    hero.setObjectName("heroMark")
    window.welcome_identity = QFrame()
    window.welcome_identity.setObjectName("welcomePresence")
    identity = QHBoxLayout(window.welcome_identity)
    identity.setContentsMargins(12, 8, 16, 8)
    identity.setSpacing(12)
    identity.addWidget(hero)
    invitation = QVBoxLayout()
    invitation.setSpacing(7)
    eyebrow = label("DÜŞÜNMEK İÇİN BİR ALAN")
    eyebrow.setObjectName("eyebrow")
    invitation.addWidget(eyebrow)
    title = label("Aklında ne var?")
    window.welcome_title = title
    title.setWordWrap(True)
    title.setTextFormat(Qt.TextFormat.PlainText)
    title.setObjectName("welcomeTitle")
    invitation.addWidget(title)
    subtitle = label("Bir fikir, bir soru, yarım kalan bir iş.\nBirlikte devam edelim.")
    window.welcome_subtitle = subtitle
    subtitle.setWordWrap(True)
    subtitle.setObjectName("subtitle")
    invitation.addWidget(subtitle)
    identity.addLayout(invitation, 1)
    welcome.addWidget(window.welcome_identity)
    welcome.addStretch(2)
    suggestions = QHBoxLayout()
    suggestions.setSpacing(10)
    for name, caption, description, shortcut, callback in (
        ("copy", "Panoyu incele", "Kopyaladığın içerikle çalış", "Ctrl+Shift+V", window.analyze_clipboard),
        ("web", "Bir konuyu araştır", "Kaynaklarla daha derine in", "/web", window.start_research),
        ("mic", "Sesli konuş", "Aklındakini anlat", "F2", window.toggle_voice_recording),
    ):
        item = ActionCard(name, caption, description, shortcut, callback, ui)
        suggestions.addWidget(item, 1)
    welcome.addLayout(suggestions)
    first_steps = QHBoxLayout()
    window.introduction_button = control("chat", "Nexus ile tanış", window.open_introduction, "Tanışalım")
    first_steps.addWidget(window.introduction_button)
    first_steps.addWidget(control("copy", "Örnek belgeyle dene", window.try_sample_document, "Örnek belgeyle dene"))
    first_steps.addWidget(control("settings", "Bağlantı kurulumu", window.open_onboarding, "Bağlantı kurulumu"))
    first_steps.addStretch()
    welcome.addLayout(first_steps)
    content_layout.addWidget(window.welcome, 1)

    window.response_bar = QWidget()
    response_layout = QHBoxLayout(window.response_bar)
    response_layout.setContentsMargins(0, 0, 0, 0)
    window.inline_avatar = CompanionAvatar(64)
    response_layout.addWidget(window.inline_avatar)
    heading = QLabel("Nexus")
    heading.setObjectName("responseHeading")
    response_layout.addWidget(heading)
    window.question_label = StatusLabel()
    window.question_label.setObjectName("modelStatus")
    response_layout.addWidget(window.question_label, 1)
    window.activity_indicator = ActivityDots()
    window.activity_indicator.hide()
    response_layout.addWidget(window.activity_indicator)
    window.copy_button = control("copy", "Yanıtı kopyala", window.copy_response)
    response_layout.addWidget(window.copy_button)
    window.response_bar.hide()
    content_layout.addWidget(window.response_bar)
    window.output_browser = QTextBrowser()
    window.output_browser.setObjectName("output")
    window.output_browser.setOpenExternalLinks(True)
    window.output_browser.setAcceptDrops(False)
    window.output_browser.setFont(QFont("Segoe UI", 11))
    window.output_browser.document().setDefaultStyleSheet(
        "p { margin-top: 4px; margin-bottom: 14px; line-height: 145%; }"
        "h1,h2,h3 { color: #f0eeea; margin-top: 20px; }"
        "a { color: #acd8bf; } pre { background-color: #252a2e; }"
        "code { font-family: Consolas; }"
    )
    window.output_browser.hide()
    content_layout.addWidget(window.output_browser, 1)
    chat_columns.addWidget(transcript, 1)
    window.presence_panel = QFrame()
    window.presence_panel.setObjectName("presencePanel")
    window.presence_panel.setFixedWidth(168)
    presence = QVBoxLayout(window.presence_panel)
    presence.setContentsMargins(12, 18, 12, 18)
    presence.setSpacing(10)
    presence.addStretch()
    window.activity_logo = CompanionAvatar(140)
    presence.addWidget(window.activity_logo, 0, Qt.AlignmentFlag.AlignCenter)
    window.presence_title = QLabel(ui("Nexus hazır"))
    window.presence_title.setObjectName("presenceTitle")
    window.presence_title.setWordWrap(True)
    window.presence_title.setAlignment(Qt.AlignmentFlag.AlignCenter)
    presence.addWidget(window.presence_title)
    window.presence_status = StatusLabel(ui("Bir soru sor veya araç seç."))
    window.presence_status.setObjectName("presenceStatus")
    window.presence_status.setAlignment(Qt.AlignmentFlag.AlignCenter)
    presence.addWidget(window.presence_status)
    presence.addStretch()
    window.presence_panel.hide()
    chat_columns.addWidget(window.presence_panel)
    root.addWidget(content, 1)
    window.speech_caption = QLabel()
    window.speech_caption.setObjectName("subtitle")
    window.speech_caption.setTextFormat(Qt.TextFormat.RichText)
    window.speech_caption.setWordWrap(True)
    window.speech_caption.setMaximumHeight(60)
    window.speech_caption.hide()
    content_layout.addWidget(window.speech_caption)

    composer = ComposerFrame()
    window.composer = composer
    composer.setObjectName("composer")
    composer_layout = QVBoxLayout(composer)
    composer_layout.setContentsMargins(14, 8, 10, 7)
    composer_layout.setSpacing(3)
    window.input_line = HistoryLineEdit()
    window.input_line.setAcceptDrops(False)
    ui.bind(window.input_line, "setPlaceholderText", "Nexus'a bir şey sor…")
    ui.bind(window.input_line, "setAccessibleName", "Nexus komut alanı")
    ui.bind(window.input_line, "setAccessibleDescription", "Mesajınızı yazıp Enter'a veya gönder düğmesine basın.")
    window.input_line.setMinimumHeight(36)
    window.input_line.installEventFilter(composer)
    window.input_line.returnPressed.connect(window.send_message)
    entry = QHBoxLayout()
    entry.addWidget(window.input_line, 1)
    window.send_button = control("send", "Mesajı gönder · Enter", window.send_message, primary=True)
    window.send_button.setFixedSize(40, 40)
    entry.addWidget(window.send_button)
    composer_layout.addLayout(entry)
    window.document_hint = StatusLabel()
    window.document_hint.setObjectName("attachmentHint")
    window.document_hint.hide()
    composer_layout.addWidget(window.document_hint)
    window.context_button = MotionButton()
    window.context_button.setObjectName("contextButton")
    window.context_button.setCursor(Qt.CursorShape.PointingHandCursor)
    window.context_button.clicked.connect(window.analyze_clipboard)
    window.context_button.hide()
    composer_layout.addWidget(window.context_button)
    tools = QHBoxLayout()
    tools.setSpacing(5)
    tools.addWidget(control("plus", "Belge ekle", window.import_document, "Ekle"))
    tools.addWidget(control("web", "Web araştırması", window.start_research, "Araştır"))
    menu_button = control("more", "Sohbet araçları", lambda: None, "Araçlar")
    menu = QMenu(menu_button)
    window.private_btn = action(menu, "Özel oturum", window.toggle_private_session)
    window.private_btn.setCheckable(True)
    window.knowledge_btn = action(menu, "Belgelerimden yanıtla", window.toggle_knowledge)
    window.knowledge_btn.setCheckable(True)
    window.speaker_btn = action(menu, "Yanıtları seslendir", window.toggle_tts)
    window.speaker_btn.setCheckable(True)
    window.speaker_btn.setChecked(window.tts_enabled)
    menu.addSeparator()
    action(menu, "Nexus ile tanış", window.open_introduction)
    action(menu, "Hafızamı göster", window.show_remembered_context)
    action(menu, "Hafızayı yönet · adayları incele", lambda: window.open_memory_manager())
    menu_button.setMenu(menu)
    tools.addWidget(menu_button)
    window.private_pill = control("shield", "Özel oturum · geçmişe kaydetme", window.toggle_private_session, "Özel oturum")
    window.private_pill.setObjectName("modePill")
    window.private_pill.setCheckable(True)
    tools.addWidget(window.private_pill)
    tools.addStretch()
    window.stop_btn = MotionButton()
    ui.bind(window.stop_btn, "setText", "Durdur")
    ui.bind(window.stop_btn, "setAccessibleName", "Durdur")
    window.stop_btn.setObjectName("stopButton")
    window.stop_btn.clicked.connect(window.cancel_active_response)
    window.stop_btn.hide()
    tools.addWidget(window.stop_btn)
    window.mic_btn = control("mic", "Sesli konuş · F2", window.toggle_voice_recording)
    window.mic_btn.setCheckable(True)
    tools.addWidget(window.mic_btn)
    composer_layout.addLayout(tools)
    root.addWidget(composer)

    window.footer_widget = QWidget()
    window.footer_widget.setObjectName("footer")
    footer = QHBoxLayout(window.footer_widget)
    footer.setContentsMargins(0, 0, 0, 0)
    footer.setSpacing(10)
    window.local_badge = QLabel(ui("YEREL MODEL"))
    window.local_badge.setObjectName("localBadge")
    footer.addWidget(window.local_badge)
    preferences = settings_store.load()
    selected = next((p for p in preferences.providers if p.id == preferences.selected_provider_id), None)
    name = selected.selected_model if selected else ""
    window.model_status = StatusLabel(name.rsplit("/", 1)[-1] if name else ui("Ayarlar'dan bir model seç"))
    window.model_status.setObjectName("modelStatus")
    footer.addWidget(window.model_status, 1)
    window.wake_button = MotionButton("Hey Nexus")
    window.wake_button.setObjectName("wakeButton")
    ui.bind(window.wake_button, "setAccessibleName", "Hey Nexus dinlemesini duraklat veya devam ettir")
    footer.addWidget(window.wake_button)
    window.connection_button = control("settings", "Bağlantı kurulumu", window.open_onboarding, "Model")
    window.connection_button.setObjectName("connectionButton")
    window.connection_button.setFixedHeight(24)
    footer.addWidget(window.connection_button)
    hint = label("Alt + Space")
    hint.setObjectName("footerHint")
    footer.addWidget(hint)
    root.addWidget(window.footer_widget)
    window.setStyleSheet(STYLE)
    window.input_line.textChanged.connect(window._sync_send_button)
    window.send_button.setEnabled(False)
    window.setTabOrder(window.input_line, window.send_button)
    window.setTabOrder(window.send_button, window.mic_btn)
