"""Rolling summaries generated by the selected local model."""

from __future__ import annotations

import json
from typing import Any

import httpx

from backend.conversations import ConversationRepository, conversation_repository


async def update_rolling_summary(
    *,
    kind: str,
    scope_id: str,
    user_text: str,
    assistant_text: str,
    chat_url: str,
    model: str,
    headers: dict[str, str],
    repository: ConversationRepository = conversation_repository,
) -> str:
    current = repository.summary(kind, scope_id)
    previous = current["summary"] if current else ""
    count = int(current["source_message_count"]) if current else 0
    prompt = (
        "Update the compact factual summary. Preserve durable decisions, unresolved work, "
        "and user preferences. Remove obsolete details. Do not add facts. Return JSON only.\n\n"
        f"PREVIOUS SUMMARY:\n{previous or '(none)'}\n\n"
        f"NEW USER MESSAGE:\n{user_text[:5000]}\n\n"
        f"NEW ASSISTANT MESSAGE:\n{assistant_text[:5000]}"
    )
    payload: dict[str, Any] = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You maintain compact Nexus context summaries."},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0,
        "max_tokens": 1000,
        "response_format": {"type": "json_object"},
    }
    async with httpx.AsyncClient(timeout=90.0) as client:
        response = await client.post(chat_url, json=payload, headers=headers)
        response.raise_for_status()
        result = response.json()
    choices = result.get("choices") or []
    raw = ((choices[0].get("message") or {}).get("content") if choices else "") or ""
    try:
        summary = str(json.loads(raw).get("summary", "")).strip()
    except (ValueError, TypeError, AttributeError):
        summary = ""
    if not summary:
        raise ValueError("The local model returned an invalid summary.")
    repository.upsert_summary(kind, scope_id, summary, count + 2)
    return summary
